arrowParens: avoid
bracketSpacing: true
jsxBracketSameLine: false
printWidth: 120
proseWrap: preserve
requirePragma: false
semi: true
singleQuote: true
tabWidth: 4
trailingComma: all
useTabs: true
overrides:
  - files: "*.json"
    options:
      printWidth: 200
